spec/translate/translate.nonStringKeys.spec.js, src/i18next.translate.js, test/server/i18next.translate.spec.js, test/test.js
accidentally you give i18n a number key, try to support it.
=> add support on key is a number

i18next.amd.js, i18next.amd.withJQuery.js, i18next.commonjs.withJQuery.js, i18next.js, release/i18next-1.8.2.js, release/i18next-latest.js, release/i18next.amd-1.8.2.js, release/i18next.amd-latest.js, release/i18next.amd.withJQuery-1.8.2.js, release/i18next.amd.withJQuery-latest.js, release/i18next.commonjs.withJQuery-1.8.2.js, release/i18next.commonjs.withJQuery-latest.js, src/i18next.detectLanguage.js
When  ```useCookie``` is set ```false```, querystring is empty, ```detectLngFromLocalStorage``` is true, throws error on below line because ```localStorage``` returns ```null``` for the key ```i18next_lng``` 
https://github.com/i18next/i18next/blob/30537bee5416644c6a1dbacb19ce5857b037a9f3/src/i18next.detectLanguage.js#L57
=> Null check for detectLngFromLocalStorage

sample/package.json, sample/readme.md, sample/server.js, sample/static/index.html, sample/static/readme.txt
Hi,
I've added simple nodejs server to the sample folder to make it easy to run this in the browser, so beginners can get up and running faster! :)
=> add nodejs static server to sample folder 

src/i18next.init.js, src/i18next.nojquery.js
This was a quick solution, something nicer can be worked directly into i18next but I leave it to the creators to know how to best do that.
=> Adds jquery like functionality without the jquery plugin.

src/i18next.functions.js
Possible bug, please, check it
=> `resource` to `resources` in addResources function

typescript/i18next.d.ts, typescript/lib/expect.js/expect.js.d.ts, typescript/lib/jquery.d.ts, typescript/lib/js-fixtures/fixtures.d.ts, typescript/lib/sinon.d.ts, typescript/tests/i18next.d.tests.ts
Please merge this pull request to resolve #421 (and #448, that is subset of #421). After merging this pull request, there are no TypeScript errors when running `tsc typescript\i18next.d.ts` (where tsc is TypeScript compiler - version 1.6.2 to be specific)
=> Resolves issue #448 - TypeScript errors

package.json
As I see, it can't break anything
fixes #477
=> Change point to main file

i18next.js
array consists of rtl langs not ltr
also indexOf returns -1 when not found, and 0+ if found, so simple if was returning true for all languages not mentioned in this array and ar (index 0).
=> Bug in RTL lang detection

src/i18next.jquery.js
So if the data label/options are changed its reflected in the i18n
=> Fix to get the updated data values for version 1.11.x with jquery.

src/i18next.js
I'm not sure is this the best way to fix it. And I reran all the tests, all passed.
#833
=> Create an new translator when clone i18next instance

src/Interpolator.js, test/interpolation.spec.js
* Adds the option to provide a custom escape function for interpolation
* Converts single-quotes in nesting to double-quotes for JSON parsing
=> Custom escape function, single-quotes in nested

CHANGELOG.md, src/Interpolator.js, src/defaults.js, test/interpolation.spec.js
#957 add setting maxReplaces in interpolation options to prevent endless loop in interpolation
=> max replaces in interpolate to prevent endless loop

src/BackendConnector.js, src/CacheConnector.js, src/Interpolator.js, src/LanguageUtils.js, src/PluralResolver.js, src/ResourceStore.js, src/Translator.js, src/i18next.js, src/index.js
hey,
currently tested only in browser.
=> feat: native browser es modules via adding .js where needed

src/Interpolator.js
nested translations inherit parent's options
=> https://github.com/i18next/i18next/issues/1009

src/Interpolator.js, test/interpolation.spec.js
This fix is same as done for i18next/react-i18next#242
=> Remove unnecessary warning when value is empty string

src/ResourceStore.js, src/Translator.js, test/translator/translator.translate.separator.spec.js
=> Allow falsy keySeparator in i18next.t

src/Translator.js, test/translator/translator.translate.missing.spec.js
To solve https://github.com/i18next/i18next/issues/1071
=> Authorize zero for saveMissingPlurals

src/Interpolator.js
=> added options as arg to missingInterpolationHandler

src/i18next.js, src/utils.js, test/i18next.promises.spec.js
solves: https://github.com/i18next/i18next/issues/661
=> Adds promises API

src/defaults.js, test/i18next.defaults.spec.js
=> Support interpolation for defaultValue as parameter

index.d.ts
=> fix init() attributes typings

.npmignore, tsconfig.json
Found myself to have time for this
resolve #1169
=> fix: tsconfig typo and npmignore

index.d.ts, test/typescript/i18next-tests.ts
This remains https://github.com/i18next/i18next/pull/1168.
- add WithT inteface and the test
/related https://github.com/i18next/react-i18next/pull/665
=> Pull up WithT interface allowing for overrides

index.d.ts
I'd like to have a more specific type for t function.
Am I wrong or it's always a "string" ?
=> Improve t function return type

index.d.ts, test/typescript/interpolator.test.ts
**Notes:** if someone wants to run typescript tests in watch mode
```bash
npm -g install nodemon
nodemon --watch 'index.d.ts' --watch 'test/**/*.ts*' --exec 'npm run test:typescript'
```
=> feat(definitions): add Interpolator interface

src/BackendConnector.js, src/ResourceStore.js, src/Translator.js, src/i18next.js
=> <=IE10 fix (unable to call parent constructor)

index.d.ts
=> types(ReactOptions): Add missing props to React Options interface

index.d.ts, test/typescript/t.test.ts
=> Allow null as TResult

index.d.ts, test/typescript/modules.test.ts
=> use() should accept a class or object

src/Interpolator.js, test/interpolation.spec.js
Cope with null value as well as undefined :)
=> Cope with null interpolation

index.d.ts, test/typescript/t.test.ts
Example: `i18n.t('MyKey', 'My value {{value}} with interpolation', {value: 3})`
=> Allow TFunction to receive 1-3 parameters

src/i18next.js, test/i18next.spec.js
This is a possible fix for #1324
=> Fixed default value as string in IE

index.d.ts, test/typescript/init.test.ts
update index.d.ts with the public getDataByLanguage API interface.  Basically this allows typescript to call the API that already exists. No functionality change.
Closes #1273
=> add getDataByLanguage into index.d.ts

src/Interpolator.js, test/interpolation.spec.js
=> Add ability to use commas in nested keys

src/i18next.js
should fix: https://github.com/i18next/i18next/issues/1413
should fix: https://github.com/i18next/i18next-express-middleware/issues/210
=> fix hasLoadedNamespace for cloned instances

index.d.ts, test/typescript/init.test.ts
=> Add store events to typings

src/PluralResolver.js
currently it's mixed == and ===
=> use == everywhere in the rules

src/LanguageUtils.js, test/languageUtils.spec.js
=> special handling for custom language -x- in getScriptPartFromCode

src/LanguageUtils.js, test/languageUtils.spec.js
=> getBestMatchFromCodes: use fallbackLng if nothing found, fixes #1470

src/Translator.js, test/i18next.interpolation.nesting.spec.js
=> fix nesting recursion #1479

src/utils.js, test/resourceStore.spec.js
=> fix prototype pollution

src/Interpolator.js, test/i18next.interpolation.skipOnVariables.spec.js
=> Extend skipOnVariables

index.d.ts, src/i18next.js, test/i18next.spec.js
=> make resource manipulation functions chainable

package-lock.json, package.json, rollup.config.js
=> chore: update build dependency (use @rollup/plugin-babel)

src/i18next.js
=> fix for cases when calling changeLanguage before finished to initialized

index.d.ts, test/typescript/init.test.ts
https://github.com/i18next/i18next/issues/1589
=> Add ignoreJSONStructure to type declaration file (InitOptions and getResource)

src/PluralResolver.js
=> fix plural equations for Kazakh

README.md
=> Update of invalid links in the README.

src/BackendConnector.js, test/backend/backendConnector.perf.spec.js
=> Reduce CPU usage loading large numbers of items

src/BackendConnector.js, test/backend/backendConnector.parallel.spec.js, test/backend/backendMockSleepy.js
Fixes #1769
- https://github.com/i18next/i18next-gitbook/pull/196
=> Add maxParallelReads option, default 10

CHANGELOG.md
=> docs: correct some links of PRs and issues

src/i18next.js, src/logger.js
when cloning i18next instance, also clone logger
should address #1819 
not sure we should allow this...?
=> clone also logger when cloning i18next

index.d.ts
=> Revert "FallbackLng function argument should also return false"

example/typescript/@types/i18next.d.ts, example/typescript/i18n/config.ts, example/typescript/i18n/en/ns1.json, example/typescript/i18n/en/ns2.json, example/typescript/index.ts, example/typescript/package.json, example/typescript/tsconfig.json
=> Add typescript example

karma.backward.conf.js, karma.conf.js
=> fix test:root without --no-sandbox is not supported

index.d.ts, package.json
=> #1978: fix type error

i18next.js, src/PluralResolver.js
fix js error on: 
[!] (plugin at position 8) SyntaxError: Unexpected token (1132:14) in node_modules/i18next/dist/esm/i18next.js
node_modules/i18next/dist/esm/i18next.js (1132:14)
catch is missing err var
- [ x] only relevant code is changed (make a diff before you submit the PR)
- [ x] run tests `npm run test`
- [ x] tests are included
- [ x] commit message and code follows the [Developer's Certification of Origin](https://github.com/i18next/.github/blob/master/CONTRIBUTING.md)
- [x ] only relevant documentation part is changed (make a diff before you submit the PR)
- [ x] motivation/reason is provided
- [ x] commit message and code follows the [Developer's Certification of Origin](https://github.com/i18next/.github/blob/master/CONTRIBUTING.md)
=> add err to catch to avoid js error during execution

test/typescript/array-access/i18next.d.ts, test/typescript/array-access/t.test.ts, typescript/t.d.ts, typescript/t.v4.d.ts
Fixes #2103 - the test I wrote as minimal of an example as I could write. To be quite honest: I'm not sure *why* this broke or why this fixes it, but as the fix removes some unnecessary code duplication, I guess it's a good change anyway.
=> fix issue with key prefixes

typescript/t.d.ts
https://github.com/i18next/i18next/issues/2138#issuecomment-2037843106
=> Fix typing performance regression

src/Formatter.js
Some simple size optimizations, there are no breaking logic or syntax changes.
=> perf: Optimize size of Formatter

src/BackendConnector.js, src/Interpolator.js, src/LanguageUtils.js, src/ResourceStore.js, src/Translator.js, src/defaults.js, src/i18next.js, src/logger.js, src/utils.js
Adds a isString utility just like in https://github.com/i18next/react-i18next/pull/1763 to reduce code duplication. This alone reduces the size of the minified output by roughly 0.5 kB.
=> perf(size): Adds a isString utility

index.d.mts
I have noticed a small typo in the type definitions. I hope that's not a breaking change :)
=> fix: Small typo in the type definitions

src/i18next.js, test/runtime/i18next.test.js
=> try to address #2270 by cloning the store data

src/i18next.js, test/runtime/i18next.test.js
Fix https://github.com/i18next/i18next/issues/1605
=> Fix multiple changeLanguage calls may resolve to a wrong language
