src/i18next.api.js

Hi,
customLoad option is a great feature.
In angularjs context, it's necessary to use $http in place of jQuery or xmlhttprequest for unit testing.
But it's not DRY to copy applyReplacement method that handle a lot of code to prepare resource url.
Give visibility to function is really useful in conjunction with customLoad and unit testing.
Regards

public visibility of applyReplacement function

---

spec/init.spec.js
spec/init/init.getResourceBundle.spec.js
src/i18next.api.js
src/i18next.functions.js

I've added a new API function 'getResourceBundle' which will return the resources of a specific bundle.
The function takes two arguments, a language and an optional namespace. When no namespace is provided, is will use the default namespace taken from the options. This is consistent with other functions like addResourceBundle and removeResourceBundle. It will return the bundle resources or an empty object when the bundle does not exist. It returns a clone of the bundle, to prevent the bundle from being changed.
I've added tests for it.

Added getResourceBundle to API. #334

---

package.json
src/i18next.exports.jquery.js

`module.exports = i18n;` was missing. `require('i18n-client/i18next.commonjs.withJQuery.js')` would return `{}`
The rest is just simplification.

Fix CommonJS with jQuery export

---

package.json

This is the format npm leaves a package.json file in when (un)installing with `--save[-dev]` flag. Changing to this format will help reduce the scope of diffs when installing new modules.

Convert package.json to npm default format

---

src/i18next.defaults.js

There are places in code where the namespaces are referenced by `o.ns.namespaces` which throws an error if init has not been run - in particular on `init.addResourceBundle` throws "Cannot call method 'indexOf' of undefined", which is difficult to debug. Setting the default values as the expected structure prevents this error.
*Note: I would add a failing test, but it's not possible to "uninitialise" to create the required state. Sorry.*

Default namespace options to expected structure

---

spec/functions.spec.js
spec/functions/functions.noConflict.spec.js
src/i18next.api.js
src/i18next.exports.js
src/i18next.functions.js
src/i18next.js
test/libs/fake.conflict.lib.js
test/test.js
testacular.conf.js

Added ```.noConflict()``` function to the public API. This works much like ```jQuery.noConflict()```.
When called, this method renames ```window.i18n``` to ```window.i18next```.
**Note:**
Even when there is no conflicting global, this method *will* rename the ```window.i18n``` global. Use carefully.

.noConflict() functionality

---

package.json

Running existing command of `testacular start` fails with error `testacular: not found`. Swap this for `grunt test`.
*Note: the tests still seem to be failing - I will investigate further and possbly add more commits to this PR if it's obvious*

Change test command in package.json

---

spec/init/init.namespace.spec.js
src/i18next.translate.js

Falling back to default namespace works ok with namespace as a prefix because the prefix is stripped as part of the pass through `_find` in the first instance. However if the namespace is defined as part of the options parameter then it is still present on the options for the second (fallback) call to `_find`.
Fix by setting the namespace explicitly to the default namespace when passing through to the fallback call to `_find`.

Fix fallback to default namepsace when namespace passed as an option

---

src/i18next.sync.js

Because HTML5 AppCache will obviously not fetch from cache when busting the url for the resource bundle. 
I could not see any other place that uses cache = true for ajax helper which resides in i18next.helpers.js on line 198. 
The configuration options should probably also receive a rename since it is now just called "cache" to something more explicit.

Expose cache busting option from configuration options

---

src/i18next.defaults.js
src/i18next.translate.js

I think it's sensible to display the key (sometimes people use English string or whichever default language they use as key) instead of an empty string.

Allow to fallback to key when trans string is empty

---

src/i18next.api.js
src/i18next.init.js

Hello, 
This is just a proposal, I still need to figure how to add unit tests :sweat_smile: 
I'm using i18next with browserify in several projects, they work fine separately, but once loaded on the same web page, calling `init` several times produces unexpected results, which seems to be normal given how it is intended to work. 
Right now I have a workaround using `hasResourceBundle` to call `init` only once, but it's not really clean. 
This is why I propose to add a `isInitialized` method to the public API. 
What do you think? 
If you find it interesting, I'll continue the work on this PR. 
Cheers, 
Alex.

Add isInitialized method.

---

src/i18next.defaults.js
src/i18next.sync.js

Add the ability to set timeout in the ajax request.
I would like to be able to set timeout for the ajax requests when fetching the translations.
If the file path is down, then I would like the default fallback to kick in where i18next displays the string key.

#386: support for adding timeout in configuration

---

license
package.json

Added the official license header according to http://opensource.org/licenses/MIT. This will be of great help for preventing legal issues for users of this library. Would be great if you can merge it.

Added official MIT header to license

---

src/i18next.helpers.js

The documentation state in features that you can give the `fallbackLng` option during translation but it does not seem to work. I noticed calls to `toLanguages` with 2 arguments (`lng` & `fallbackLng`) but this function did not seem to handle this case properly so I added some code to do it.
Careful: the option fallbackLng still does not work when the `lng` option is not provided during initialization. I added a hack in my code to provide it in all cases because I did not have the time to fix this case too.

fix fallback lng option during translations

---

src/i18next.init.js
src/i18next.sync.js

It works but it's far to be perfect ;)
The init callback function doesn't respect the standard : it should pass the err object as the first argument, and the 't' object as the second.
For the moment, the only way to distinguish error from translate object (t) is to test the type of the argument...
````
$.i18n.init(i18nOption, function(t){  
// error handling...
if (typeof(t) === 'string'){ 
return console.error(t); 
}
// Continue if there isn't any error :)
});
````

Forward the error from sync fetch methods to the init callback function

---

spec/translate/translate.interpolation.spec.js
src/i18next.translate.js

The interpolation resolution code inside translate.js is looping over
each key in the interpolation dictionary and applying the replacements
one at a time. This means that if untrusted user input contains the name
of another key in the dictionary, for example `'__lastName__'`, an
unexpected interpolation can happen:
````
i18n.t('__firstName__ __lastName__', {
firstName: '__lastName__',
lastName: 'foo',
});
// equals "foo foo"
````
This combines with the unescaping suffix feature to cause XSS injection,
even with escapeInterpolation set to true. For example,
````
i18n.t('__firstName__ __lastName__', {
escapeInterpolation: true,
firstName: '__lastNameHTML__',
lastName: '<script>',
});
// equals "<script> &lt;script&gt;"
````
This PR fixes that by performing the replacements *all at the same …

Reimplement XSS-vulnerable sequential replacement code

---

src/i18next.plurals.js

I had initially generated [i18next/i18next-ios](https://github.com/i18next/i18next-ios) plural rules from the javascript rules. And today after enabling a warning to spot dead code, I found this issue with the mnk definition. Hence I'm submitting this trivial patch ;)

Fixed mnk plural definition

---

src/i18next.sync.js

With this patch it is possible to include a "headers" option when calling i18n.init() which may be used to override the default content-type and accept headers or to provide additional custom HTTP headers.
Example usage:
i18n.init({
headers: {'content-type': 'application/json'}
});

Add support to override Ajax HTTP headers

---

spec/functions/functions.postprocessor.spec.js
src/i18next.translate.js
test/server/i18next.functions.spec.js
test/test.js

I found out that multiple post processes are not applied for the case of missing value. This should fix it. Let me know if I need to add anything.

Runs multiple post processes for missing translations

---

src/i18next.translate.js

It is in some cases useful to have a different `keyseparator` for some of the translations. In our case, we moved to using English message as the key, so we had to change the `keyseparator` to something like `:::` (which will not occur in regular message).

Add nsseparator and keyseparator as options to translation function

---

spec/translate/translate.sprintf.spec.js
src/i18next.translate.js
test/backward/compat.js
test/server/i18next.translate.spec.js
test/test.js

Do not overwrite first sprintf argument when it is falsey. Also,
fix bad falsey check in _translate.
Resolves #451

Fix use of sprintf as shortcutFunction when first argument falsey

---

src/ResourceStore.js

I've got a use case where some users are allowed to update the translations, which works fine using
`i18next.addResource(i18next.language, ns, key, translation)`. I'd like to listen to these changes, but unfortunately the `added` event emitted by `i18next.store` (docs seem to be incorrect [stating that it's emitted by i18next](http://i18next.com/docs/api/#on-added)) doesn't specify the key being added/updated.
This PR makes event listeners also receive key, along with value in case it could be useful. The latter could be removed if undesired.

Include key and value in 'added' event if adding a single resource

---

src/Translator.js
test/translator/translator.translate.combination.spec.js
test/translator/translator.translate.context.spec.js

Fixes detection when using both context and pluralization and context not found. It now will fallback to default plural if no context is found.
Possible key list order:
key_context_plural
key_context
key_plural
key

Fixes detection when using both context and pluralization and context not found.

---

src/i18next.js

On each invocation, the function returned by `i18next.handle` adds the given language to the `i18next.options.preload` array without checking for doubles, and then goes on to load resources for all elements of that array. Over time, the preload array becomes huge, and because it is constantly iterated, this leads to a noticeable linear decrease in performance.
This PR is an attempt to fix that situation. It will only add a language to the `i18next.options.preload` array when it is not yet present, and it will call `loadResources` only when a new language has actually been added.

Only add language to preload array when not yet present

---

src/Interpolator.js
test/interpolation.spec.js

corresponding pull request for issue: https://github.com/i18next/i18next/issues/747 .
please review and let me know what you think. Thanks!

fixed an issue with several unescaped key in the interpolation string

---

src/Interpolator.js
test/interpolation.spec.js

If we define a custom formatter function which raises an exception, this one can be handled but let a wrong Interpolator state leading to an error on the next translation loop.

Fix Interpolator formatter exception error propagation due to not reset RegExp indices

---

src/Interpolator.js
test/interpolation.spec.js

I found that if I pass any `interpolation` options without including `escapeValue`, `this.escapeValue` will get set to `undefined` in `Interpolator`. The documentation indicates `escapeValue` defaults to `true`, so this could cause variables to not be escaped as expected in some cases.
This config, for example, will result in `i18next` not escaping variables as expected:
```
i18next.init({
interpolation: {
prefix: "__",
suffix: "__"
},
...
});
```
It's worth noting that it could potentially be a XSS security issue for users of `i18next` if they believe variables are getting escaped when they actually aren't.

Fix Interpolator.escapeValue defaulting to undefined in some cases

---

package.json

See https://github.com/webpack/webpack/issues/1979
This seems to be the preferred way to indicate where ES6 modules reside now.

Add module entry in package.json

---

src/LanguageUtils.js

This special case handling prevents from dealing with "nb" and "nn" as different languages, which they are.
I think it should be up to the user to define "no" as fallback language for "nb" and "nn" if they want to. It should not be enforced.

Removed special cases for norwegian

---

src/index.js

export all functions off i18next to allow desctructuring i18next imports `import { t } from 'i18next';`

fix #873 allow desctructuring for es6 modules imports

---

src/Translator.js

Hello,
When the result of a translation is an object (_Object, Array, etc_) and the copy is done, the translation function loops over all object's properties, even those that might be inherited and could not not have a translation.
We should use `hasOwnProperty` to not translate these properties.

Fix: iterating over object's own properties

---

src/Translator.js
test/translator/translator.translate.combination.spec.js

This PR adds a new option while running translation function.
- nest: if nest === false, nesting at interpolations will be disabled in this translation.
Example:
```js
i18next.t('result', {
userInput: '$t(result)',
result: 'random value',
nest: false,
});
```
```json
{
"result": "Your input is {{userInput}} and the execution result is {{result}}"
}
```
The result of this will be `Your input is $t(result) and the execution result is random value` instead of a `RangeError: Maximum call stack size exceeded`.
Note: This option is disabled by default, you need to call it explicitly with false as parameter to disable nesting. Any other value than false will not enable this option.
---
Closes: #917

Add nest option to translation function

---

src/i18next.js

The async support broke changeLanguage() function, so that languageChanged would not get emmitted, unless language was directly given to the function as parameter. Thus language detectors would not trigger the event.

Fix languageChanged not getting emitted on initial load.

---

.gitignore
src/i18next.js

As mentioned in [documentation](https://www.i18next.com/api.html#getfixedt):
> Both params could be arrays of languages or namespaces and will be treated as fallbacks in that case.
Also I'm confused about "will be treated as fallbacks in that case" part because parameters of `getFixedT` are not used to fallback language or namespace.

getFixedT lng parameter of array type

---

src/ResourceStore.js
test/resourceStore.spec.js

Issue #1022 
Sometimes you want to load resource bundles in background without triggering events and re-rendering the whole app (ie. with react-i18next).
Added an optional parameter to addResources() and addResourceBundle() (`option = { silent: false}`), similar to addResource(), to ignore the emitting of 'added' event.

Added options.silent to addResources and addResourceBundle

---

src/defaults.js

This replaces Array.push with Array.concat in order to avoid mutation. This prevents the issue described in #1036.

Avoid mutating whitelist array. Fixes #1036

---

src/EventEmitter.js
test/eventEmitter.spec.js

Currently, it spread all the arguments because of how `concat` works but this is fixed in this PR.
e.g if you pass `emitter.emit('event', ['en', 'pt'], 'key')` it was resulting in args as `'en', 'pt', 'key'`. This PR fixes the arguments to result in `['en', 'pt'], 'key'` while listening to wildcard. Previous behaviour breaks listening to 'missingKey' event.

Properly handle arguments containing arrays while listening to a wildcard event

---

src/Interpolator.js
test/translator/translator.translate.escape.spec.js

If custom escape function is used, then raw value (not type casted to String) can be passed to it.
This PR solves issue #1058 
New Interpolation options is added:
| option | default | description
-- | -- | --
useRawValueToEscape | false | If true, then value passed into escape function is not casted to string, use with custom escape function that does its own type check)
My example use-case: `Handlebars.Utils.escapeExpression` is used as escape function and `useRawValueToEscape` is true then escaping can be disabled for a specific value as soon as it is wrapped in Handlebars.SafeString.

Allow to pass raw value to the custom interpolation escape function

---

src/ResourceStore.js
src/i18next.js
test/resourceStore.spec.js

Simple method to return the whole language (i.e. namespaces loaded so far) from the store. Mostly so we don't have to access `resourceStore` object directly.  Closes #1086.

Add getDataByLanguage method to return language data currently in store #1086

---

src/PluralResolver.js
test/pluralResolver.spec.js

Using this [doc](http://www.unicode.org/cldr/charts/33/supplemental/language_plural_rules.html#he) as reference.
Ongoing PR for the translate documentation: https://github.com/translate/l10n-guide/pull/71/
Fixes https://github.com/i18next/i18next/issues/1120

Add Hebrew plural support

---

src/Translator.js

The translate function was breaking in cases when the passed argument to the function is an object. This should handle pretty much all of the cases.

refactor non valid keys handling

---

index.d.ts

This PR adds typings for option `transEmptyNodeValue` introduced in https://github.com/i18next/react-i18next/pull/462.

Add `transEmptyNodeValue` to `ReactOptions`

---

index.d.ts
test/typescript/t.tfunction.test.ts
test/typescript/t.witht.test.ts

I added a few cases to the tests and pass the `npm run test:typescript`. Please let me know if there is anything uncool.
PS:  
1. it may conflict with https://github.com/i18next/i18next/pull/1186, please check if my tweak is fine.
2. things like `t'key-with-${var}'` won't work with this declaration but I don't think that's a big deal

#1189 typescript - accept templatestringsarray as TKey

---

index.d.ts
test/typescript/t.test.ts

Add defaultValue tests and allow second arg string as defaultValue

---

index.js

Both import methods (`import * as i18next from 'i18next'` and `import i18next from 'i18next'`) work this way. It is necessary since the browser exports use a default export but the node ones don't.

Fix exports for node

---

index.d.ts
test/typescript/init.test.ts

Add typings for `hashTransKey` [introduced][1] in react-i18next 6.2.0.
[1]: https://github.com/i18next/react-i18next/commit/06fb359371f9c5a21eb4fd0148a7e739b5975fd1
(It might be more readable to define something like `type DefaultValue = any` and use that throughout.)

Add `hashTransKey` to `ReactOptions`

---

src/i18next.js

closes https://github.com/i18next/i18next/issues/1211
My only "question" is that i saw that you dont do `reject` on any promise here. Is that intentional?

Expose error on reloadResources

---

index.d.ts
test/typescript/init.test.ts

Hello, first contribution to the project. Ran into this earlier today when integrating with i18next:
Turns out useSuspense is not on the ReactOptions interface, but is listed in the documentation: https://react.i18next.com/latest/i18next-instance
This PR should address the above. It may also be worthwhile to add the additional options for react in init options listed in the same link above. Happy to do so at a later time.
Ran tests prior to committing and ran into this:
Which led the update to the init.test.ts file.

Add useSuspense to ReactOptions, fix error throwing on test

---

index.d.ts
test/typescript/modules.test.ts

While the plugin interfaces can't be used directly since they're not exported, it still serves as reference / documentation.

adding init function to 3rdParty module typings and enforcing type property

---

index.d.ts
test/typescript/init.test.ts

This [example with locize](https://github.com/i18next/react-i18next/blob/master/example/locize/src/i18n.js) will cause a type error.
Fixed by adding an init options for [`locize-editor`](https://github.com/locize/locize-editor) and [`locize-lastused`](https://github.com/locize/locize-lastused) plugins.

Fix type error when init with locize plugin options

---

index.d.ts
test/typescript/init.test.ts

`ResourceKey` can also be string like in this case
```
{
en: {
"logout": "Logout"
}
}
```

ResourceKey type should allow top level string value

---

src/defaults.js

To allow returning of a key when `returnObjects` is `false`. See #1234
More discussion in #1239

Disabled default returnedObjectHandler

---

index.d.ts
test/typescript/modules.test.ts

This is going to be a cascading set of changes across projects. Tightening the `use()` method args in #1291 exposed that the downstream types were incorrect, and the types here were not flexible enough to accomodate.
Closes #1294 (along with related PRs in other repos)

Correct `use(module)` types

---

index.d.ts

Required for the types for i18next-sprintf-postprocessor at DT to be updated to make use of the bundled i18next types.

Allow augmentation of TFunction to be able to add overloads

---

src/Interpolator.js

Hi!
I started to use this library and I would like to collaborate. I removed Interpolator#init `reset` param because it's just used internally in the constructor.
Cheers!

remove unused Interpolator#init reset param (only used internally)

---

index.d.ts
test/typescript/modules.test.ts

The `ReadCallback` is the same for both `read` and `readMulti` but according to the docs they expected two different values: https://www.i18next.com/misc/creating-own-plugins#backend
Code from the docs:
```javascript
read: function(language, namespace, callback) {
/* return resources */
callback(null, {
key: 'value'
});
},
// optional
readMulti: function(languages, namespaces, callback) {
/* return multiple resources - usefull eg. for bundling loading in one xhr request */
callback(null, {
en: {
translations: {
key: 'value'
}
},
de: {
translations: {
key: 'value'
}
}
});
},
```
Before this change, it would error: `Type 'string' is not assignable to type 'ResourceLanguage'`.
In the following code: 
```typescript
const backendModule: BackendModule = {
type: 'backend',
init: () => null, …
```

Incorrect callback type for backend module read callback

---

src/EventEmitter.js
test/eventEmitter.spec.js

The loop in `EventEmitter.off` is is unnecessarily expensive.
Looping over all observers and calling `indexOf` each time results in (roughly) quadratic time complexity, leading to slowdowns when lots of listeners are registered.
This solution might still not be ideal due to the `Array.slice` call and we might be better off just using `Array.filter` (it certainly would be cleaner).
Unfortunately I don't know enough about the backwards-compatibility requirements off this project to make this decision.

Improve performance of EventEmitter.off

---

src/Interpolator.js
src/utils.js
test/interpolation.spec.js

Records don't support `...` spread operator, so the previous `combinedData` implementation broke usage of Records as the localization parameters.
This also changes the test case of overriding a default value with undefined as it would be difficult (and not very valuable)
to implement that with the current `getLastOfPath`.

Support using ImmutableJS Records as the data model.

---

index.d.ts

This PR adds the missing `cleanCode` option to the `initOptions` in the TypeScript definition.

Add missing `cleanCode` option to TypeScript def

---

index.d.ts
test/typescript/exposed.test.ts

This is my interpretation of the runtime code and requires review for accuracy
Closes #1364
/cc @fromi

Type ResourceStore

---

src/Interpolator.js
test/interpolation.spec.js

Addresses #1384 
Although there isn't a compelling reason to be dependent on the old behaviour, this is technically a breaking change so I've added a new option `alwaysFormat` (not sure if this should also update the docs) which will, unimaginatively, always format values used for interpolation. This option defaults to `false` in order to preserve existing behaviour.

Add option to always format interpolated values

---

src/Interpolator.js
test/interpolation.spec.js

@mgroenhoff @jamuhl 
Now i feel guilty >_<
Initiative is really punishable :)
I hope this solves the problem https://github.com/i18next/i18next/pull/1398

Double fix for 1395 issue

---

src/i18next.js
test/i18next.use.spec.js

should make this type of errors a bit more obvious: https://github.com/i18next/react-i18next/issues/1078

check if module passed to i18next.use() has correct signature

---

src/Interpolator.js
test/i18next.translation.formatting.spec.js

For example:
```
{
"key1": "The following text is uppercased: $t(key2, uppercase)",
"key2": "some text"
}
```
```
i18next.t('key1');
// -> "The following text is uppercased: SOME TEXT"
```
If uppercase is defined as:
```
i18next.init({
interpolation: {
format: function(value, format, lng) {
if (format === 'uppercase') return value.toUpperCase();
return value;
}
}
});
```

Could we use formatting functions in the nesting 't' function?

---

index.d.ts

For `ReadCallback`, when `err` is an `Error`, the second argument should be a boolean indicating whether to retry.

Allow passing retry boolean to `ReadCallback`

---

index.d.ts
test/typescript/t.test.ts

Add the ability to pass `false` as nsSeparator & keySeparator

Allow boolean on keySeparator and nsSeparator

---

src/BackendConnector.js
src/Translator.js
test/i18next.hasLoadedNamespace.spec.js

- added additional log warn statement (useful i.e. for users using locize publishFormat = 'json_auto')
- rephrased some existing log statements

detect if translations are flat instead of nested and warn

---

src/Translator.js
test/i18next.interpolation.nesting.spec.js
test/interpolation.spec.js

Fixes: https://github.com/i18next/i18next/issues/1474
as documented here: https://www.i18next.com/translation-function/nesting#basic

fix nesting interpolation with prepended namespace, fixes #1474

---

src/PluralResolver.js
test/pluralResolver.spec.js

The problem noticed on https://treker.mk/mk/stats, fixed for the project with https://github.com/treker-mk/website/pull/28
according to https://unicode-org.github.io/cldr-staging/charts/37/supplemental/language_plural_rules.html#mk

fix: Macedonian plural formula - *11 (11, 111, 211, 311, 58711...) is plural

---

index.d.ts
test/typescript/init.test.ts

Fixes an issue I had with checking whether a certain language is already loaded without passing a namespace through `instance.hasResourceBundle(lng, ns)`.
Currently, the typings act as if you'd always receive an object with key `translation` (which might have to be fixed too, but I guess its fine for now). But if that language is not loaded yet, as [the underlying implementation just returns whatever it finds on `this.data`](https://github.com/i18next/i18next/blob/master/src/ResourceStore.js#L126), it will be undefined.

fix: getDataByLanguage typings & test

---

index.d.ts
test/typescript/exposed.test.ts

Hello there, I found that `off` method in ResourceStore and i18n had some incomplete TypeScript types (the method is inherited from parent EventEmitter)

fix type declarion of exposed EventEmitter#off methods

---

src/Translator.js
src/defaults.js
test/i18next.interpolation.skipOnVariables.spec.js

```javascript
const i18next = require('i18next')
i18next.init({
lng: 'en',
interpolation: {
skipOnVariables: true
},
resources: {
en: {
translation: {
key: 'value {{a}}',
keyWithoutVar: 'value',
nested: 'nested stuff',
keyWithNest: '$t(nested2) value',
keyWithNestAndVar: '$t(nested2) value {{a}}',
nested2: 'HI'
}
}
}
})
console.log('-----------')
console.log(i18next.t('keyWithoutVar')) // value
console.log('-----------')
console.log(i18next.t('key', { a: 'hahaha' })) // value hahaha
console.log('-----------')
console.log(i18next.t('key', { a: '$t(nested)' })) // value $t(nested)
console.log('-----------')
console.log(i18next.t('key', { a: i18next.t('nested') })) // value nested stuff
console.log('-----------')
console.log(i18next.t('keyWithNest')) // HI value
console.log('-----------')
// …
```

introduce new option skipOnVariables to fix #1479

---

index.d.ts

This resolves https://github.com/i18next/i18next/issues/1486. It also updates the default values of `bindI18n` and `bindI18nStore` attributes in `ReactOptions` type as they are described [here](https://github.com/i18next/react-i18next/blob/master/src/context.js#L3).

Change bindStore to bindI18nStore in ReactOptions type and update default values

---

src/PluralResolver.js

Add a plural resolver for locale "ht"

---

index.d.ts
src/LanguageUtils.js
test/languageUtils.spec.js

Enables a function to be specified for fallbackLng. Discussed as a solution to #1506. This function can return either of the other existing types: string, array or object.
I felt like I was adding a lot of code to test this small feature, but a smarter way to test this hasn't come to me yet.
Checklist says this will want documentation 🤔 Coming soon I think.

allow fallbackLng as function

---

package-lock.json
package.json

Hello,
@babel/runtime was not specifying file extensions ([discussed originally here](https://github.com/babel/babel/issues/8462) and [recently here](https://github.com/babel/babel/issues/12058)) which wasn't a problem until webpack 5, which was released this week, started enforcing file extensions "`where the package.json contains '"type": "module"'`" as you can see in the error snippet below
This PR addresses this error (below).
```shell
ERROR in ./node_modules/i18next/node_modules/@babel/runtime/helpers/esm/inherits.js 1:0-46
Module not found: Error: Can't resolve './setPrototypeOf' in '/Users/mustafa/code/un/foodloss-portal/node_modules/i18next/node_modules/@babel/runtime/helpers/esm'
Did you mean 'setPrototypeOf.js'?
BREAKING CHANGE: The request './setPrototypeOf' failed to resolve …
```

updated @babel/runtime to ^7.12.0 to resolve runtime file extensions issue in webpack 5

---

index.d.ts

According to this issue: https://github.com/i18next/i18next/issues/992 and code that was added, made as tweak to get 4th param in format function to be able to use it with TS.

Updated FormatFunction signature to match code

---

package.json
sample.html
test/backward/v1.11.1.compat.js

Updates a few hyperlinks in the `i18next` package definition and documentation to point directly to the HTTPS-enabled homepage.

Update i18next homepage and sample documentation links

---

index.d.ts

Fix #1550 
The `lng` parameter must be optional, to be able to run the function without any parameter to use the language detector.

Updated changeLanguage signature to match codebase

---

src/PluralResolver.js
src/Translator.js
test/pluralResolver.spec.js
test/translator/translator.translate.missing.spec.js
test/translator/translator.translate.updateMissing.spec.js

Fixes #1549
* This should at least fix default plural values sent to the backend when `updateMissing` is enabled. I'm not sure if this will _also_ fix the interpolation result described in #1549.
* Remove some test duplication

Improve updateMissing default plural behavior

---

index.d.ts

- Allow nullable "data" in BackendModule.read callback. According to the docs, callback(err, null) is valid.
- BackendModule.create is optional.
- BackendModule.readMulti should use MultiReadCallback instead of ReadCallback.

fix: type definitions

---

src/Translator.js
test/translator/translator.translate.updateMissing.spec.js

Relates to https://github.com/i18next/i18next/issues/1549
Minor followup to https://github.com/i18next/i18next/pull/1558 that fallbacks to the singular `defaultValue` if the plural variant is undefined, which resembles the previous behavior. This at least supports scenarios in which the singular and plural strings are the same.

Fallback on singular defaultValue

---

src/ResourceStore.js
test/resourceStore.fallback.spec.js
test/utils.spec.js

This PR is just for discussion...
It is not breaking anything, but increments a bit of code size and by default sets the ignoreJSONStructure flag to true (tbd).
This functionality, helps in cases where the json data is mixed nested and flat or the json data is changing, like when using auto mode for the publishFormat in locize...

introduce ignoreJSONStructure flag, to automatically lookup for a flat key if a nested key is not found an vice-versa

---

index.d.ts

This is the first PR that solves this problem: https://github.com/i18next/i18next/issues/1578
[Another one](https://github.com/locize/i18next-locize-backend/pull/340) will be created under `i18next-locize-backend` that depends on this.
It should have no breaking changes to users.

Add support to proper augment PluginOptions type

---

index.d.ts

There is the config alwaysFormat that works fine, but is missing from the types.

Add alwaysFormat into the types

---

src/Interpolator.js

Because of https://github.com/i18next/i18next/issues/1596
I'm issueing a PR to address `includes` not being supported on older browsers.

`includes` is not supported on older browsers

---

src/Translator.js
test/translator/translator.translate.returnObject.spec.js

Add 'ns' to the 'returnedObjectHandler' options
I've used the same base code from https://github.com/i18next/i18next/pull/1617 to add tests for the `returnObject = false` case
closes #1618

1618 - Add 'ns' to the 'returnedObjectHandler' options

---

index.d.ts
test/typescript/init.test.ts

In the API, i18next uses many `string[]` but has no intention to modify them (for inputs or properties), nor that user changes them (for outputs). Making them all readonly arrays make it closer to what's expected without breaking any valid usage.

fix(types): only use readonly array of strings in API

---

src/Translator.js
src/utils.js
test/translator/translator.exists.spec.js

I have used i18next, react-i18next.
However, when using the i18n object to determine the existence of the key, I found that passing one `nullish factor(undefined or null, or '')` results in the error below:
```js
TypeError
Cannot read property 'forEach' of undefined
```
I think `i18n.exist(undefined or null, or '')` should return` false`.
Similar to mine, there will be many cases that deliver nullish factors, and I think it is obvious that nullish factors do not exist as keys in the resource.

change to return false when a nullable argument is passed

---

index.d.ts
test/typescript/modules.test.ts

Changes mentioned in https://github.com/i18next/i18next/issues/1440
@rosskevin

Fix i18n.use() cannot pass module constructors in TypeScript

---

index.d.ts
src/i18next.js
test/i18next.spec.js

Adds optional `keyPrefix` parameter to `getFixedT` function in order to allows for improved developer experience when querying deeply nested keys with common prefix.
```
i18next.addResource('fr', 'translation', 'very.deeply.nested.key', 'ici!');
const t = i18next.getFixedT('fr', null, 'very.deeply.nested');
const test = t('key'); // "ici!"
```
Original GH issue (from react-i18next): https://github.com/i18next/react-i18next/issues/1359

Feature: key prefix option

---

CHANGELOG.md
index.d.ts
src/ResourceStore.js
src/i18next.js
test/i18next.spec.js

It can be used as primary used language, for example in a language switcher.

introduce new i18next.resolvedLanguage property

---

package-lock.json
package.json

Following #1651, this PR contains only the update of `i18next-localstorage-cache` and `i18next-browser-languagedetector`

Updated i18next compat dependencies

---

karma.conf.js
src/i18next.js
test/i18next.spec.js

I recently ran into #1287, and based on comments there, I saw that I'm not the only one. (In my case, I was trying to write a lower-level function that could take a `t` function either from `useTranslation` or from a I18n instance.) Since this does seem to be a somewhat common error, and since destructuring `t` or trying to use it as a callback can be useful, I believe it would make sense to bind the `t` function within the I18n constructor (similar to how React class components can bind their callbacks) so that `this` is always defined, regardless of how the `t` function is used.
While working on this PR, I fixed some typos, and I noticed that tests were failing, so I set a fixed timezone to help address that. (I can split these changes into separate PRs if you prefer.)
Thank you.

Bind i18n.t

---

src/Translator.js
test/translator/translator.translate.combination.spec.js
test/translator/translator.translate.plural.spec.js

Localizing in a specific way 0 count is a very common case.
There was a related [issue](https://github.com/i18next/i18next/issues/1220).
Also unicode documentation says: _"implementations are encouraged to provide the ability to have special plural messages for 0 in particular, so that more natural language can be used"_ https://cldr.unicode.org/index/cldr-spec/plural-rules

Add _zero suffix lookup if count === 0

---

index.d.ts

This fixes the typing and documentation of `hasLoadedNamespace`
Fixes #1723

fix typing and documentation of `hasLoadedNamespace`

---

src/Translator.js
test/translator/translator.translate.missing.spec.js

The saveMissingPlurals feature did not respect `ordinal: true` cases. Passed in options to that pluralResolver and wrote tests to catch any regression.

Fixed ordinal-suffixes for saveMissingWithPlurals

---

src/Translator.js
test/i18next.extendTranslation.spec.js

`i18next-icu` were unable to access [defaultVariables](https://www.i18next.com/translation-function/interpolation#all-interpolation-options) options.
When **not** using ICU: 
```typescript
import i18next from 'i18next';
async function main() {
const t = await i18next
.init({
resources: {
fr: {
ns: {
a: 'hello {{foo}}',
},
},
},
interpolation: {
defaultVariables: {
foo: 'BAR',
},
},
lng: 'fr',
});
console.log(t('ns:a')); // ✅ print `hello BAR`
}
main();
```
When using ICU: 
```typescript
import i18next from 'i18next';
import ICU from 'i18next-icu';
async function main() {
const t = await i18next
.use(ICU)
.init({
interpolation: {
defaultVariables: {
foo: 'BAR',
},
},
resources: {
fr: {
ns: {
a: 'hello {foo}',
},
},
},
lng: 'fr',
});
console.log(t('ns:a')); // ❌ print hello {foo}
}
main(); …
```

fix: defaultVariables were not accessible inside plugin `parse` function

---

index.d.ts
src/Translator.js
test/translator/translator.translate.spec.js
test/typescript/t.test.ts

usage: 
```js
i18next.t('key', { returnResolved: true })
// returns {
//   usedKey: 'key',
//   res: 'translation value,
//   exactUsedKey: 'key',
//   usedLng: 'en',
//   usedNS: 'translation',
// }
```
While this PR technically works to help in use cases like #1763 I'm not sure if we should offer this kind of interface...
Normally the lang HTML attribute is set to the [i18next.resolvedLanguage](https://www.i18next.com/overview/api#resolvedlanguage) value.

introduce returnResolved t option that pratically exposes the result of the resolve function

---

index.d.ts
test/typescript/init.test.ts

Fix an issue where the value and type could be different when getting Data with getDataByLanguage.
If namespace is customized, key may be other than `translation`.

fix: getDataByLanguage type

---

test/backend/backendConnector.load.retry.spec.js

- Confirm that the callback is called even when some namespaces fail completely
- While writing these tests it became very clear that there is an inability to set the retry delay etc of `read` when using `BackendConnector.load`, as noted in #1809
- All of these tests pass with the code as-is :+1:

More `BackendConnector.load` failure tests

---

index.d.ts

This PR fixes a minor type issue where the fallbackLng property from `InitOptions` accepts the following types:
``` 
false | string | readonly string[] | FallbackLngObjList
````
The fallbackLng property also accepts a function that returns a value of type:
```
(code: string) => string | readonly string[] | FallbackLngObjList
```
I'm doing some work in my dev environment where I want to disable the fallbackLng based on some condition ie. I want to extend the function return type to allow us to return `false`.
```
(code: string) => string | readonly string[] | FallbackLngObjList | false
```
This will fix what I think is an inconsistency with the fallbackLng type in InitOptions.

FallbackLng function argument should also return false

---

src/Formatter.js

This PR resolves #1841. 
Few considerations:
- maybe we should export `createCachedFormatter` as a utility function so that others may reuse it when creating custom formatters?
- I had no idea how to test that functionality apart from somehow stubbing Intl constructors and verifying that they are not called multiple times - I can try to add this test if you would like to have it
- as cache keys are always strings I decided to use object as caching structure instead of Map (which might cause compatibility issues in older browsers)

Add formatter cache

---

index.d.ts
package.json
test/typescript/returnTypes.test.ts

I forgot to move this last change here, it's more like an improvement than a fix, so we can appropriately test the `returnNull` and `returnEmptyString` options.

Fix normalize type options

---

index.d.ts
test/typescript/t.test.ts

Closes https://github.com/i18next/i18next/issues/1852

[TypeScript] Add default value for TDefaultResult

---

index.d.ts
test/typescript/custom-types/getFixedT.test.ts

Closes https://github.com/i18next/i18next/issues/1856

Make getFixedT type-safe

---

index.d.ts
test/typescript/exposed.test.ts
test/typescript/modules.test.ts

Adds TS type for `Formatter.addCached`

Add type for Formatter.addCached

---

index.d.ts
test/typescript/custom-types/i18next.d.ts
test/typescript/custom-types/t.test.ts
test/typescript/t.test.ts

Closes https://github.com/i18next/react-i18next/issues/1559, https://github.com/i18next/react-i18next/issues/1576, https://github.com/i18next/react-i18next/issues/1574
Since `returnNull` option is `true` by default, `t` function can return `string` or `null`. By declaring the `resources` type, we can infer the exact return type, so this is only useful to people who can't declare the `resource` type .
This PR allows to change this ☝️  behaviour if to set the `returnNull` type to `false`.
```ts
// i18next.d.ts
import 'i18next';
declare module 'i18next' {
interface CustomTypeOptions {
returnNull: false;
}
}
```

Change `DefaultTFuncReturn` to return `null` if `returnNull` typeOption is true

---

index.d.ts

Closes https://github.com/i18next/i18next/issues/1869

Expose some types

---

index.d.ts

Extend the `init` method with a generic parameter for backend options

---

index.d.ts

`resolvedLanguage` can be unset if i18next is initialized in `cimode` and `dev` language
https://github.com/i18next/i18next/blob/e240c0eb29b5e118df174c6ba863a570e56fa859/src/i18next.js#L306

types: fix resolvedLanguage type

---

.eslintrc
src/PluralResolver.js
src/Translator.js
test/pluralResolver.spec.js
test/translator/translator.translate.missing.spec.js
test/translator/translator.translate.plural.spec.js

instead of:
```js
// i.e. english
{
"key_one": "{{count}}st place", // 1st, 21st, 31st
"key_two": "{{count}}nd place", // 2nd, 22nd, 32nd
"key_few": "{{count}}rd place", // 3rd, 23rd, 33rd
"key_other": "{{count}}th place" // 4th, 5th, 24th, 11th
}
// ...
i18next.t('key', { count: 1, ordinal: true }); // -> "1st place"
i18next.t('key', { count: 21, ordinal: true }); // -> "21st place"
i18next.t('key', { count: 2, ordinal: true }); // -> "2nd place"
i18next.t('key', { count: 11, ordinal: true }); // -> "11th place"
i18next.t('key', { count: 32, ordinal: true }); // -> "32nd place"
```
new:
```js
// i.e. english
{
"key_ordinal_one": "{{count}}st place", // 1st, 21st, 31st
"key_ordinal_two": "{{count}}nd place", // 2nd, 22nd, 32nd
"key_ordinal_few": "{{count}}rd place", // 3rd, 23rd, 33rd …
```

prefixed ordinal keys

---

src/i18next.js

Reason: i18next 23 dropped support for older node and browsers.... The new version runs fine with recent node, but I feel there's an issue regarding the transpilation of
```javascript
class I18n extends EventEmitter {
static createInstance = (options = {}, callback) => new I18n(options, callback)
}
```
It's currently transpiled as 
```js
class em extends D {
static createInstance = function ()  {
let e = arguments.length > 0 && void 0 !== arguments[0] ? arguments[0] : {},
t = arguments.length > 1 ? arguments[1] : void 0;
return new em(e, t)
};
}
```
Runs fine from es2022 (not before) ... but browser support I'm less sure how static +  function will work (https://caniuse.com/mdn-javascript_classes_static -> 95% / but I suspect that `static = function` is a different case). 
With this PR …

refactor: static createInstance for wider browser support

---

index.d.ts
test/typescript/custom-types/getFixedT.test.ts
test/typescript/custom-types/i18next.d.ts
test/typescript/fallback-types/getFixedT.test.ts
test/typescript/fallback-types/i18next.d.ts
test/typescript/fallback-types/tsconfig.json
tsconfig.json

PR adds the feature mentioned in #1928 to allow setting a custom type for fallback namespace.

#1928: add fallbackNS type handling

---

index.d.ts

Optimizing the FallbackNs parsing process for easier understanding and maintainability.

Optimize logic for fallback ns

---

index.d.ts
test/typescript/t.test.ts

Closes https://github.com/i18next/i18next/issues/1982

Constrain return type when `returnObjects` is `true`

---

CHANGELOG.md
i18next.js
index.d.ts
src/Formatter.js
src/LanguageUtils.js
src/Translator.js
src/i18next.js
test/backend/backendConnector.load.retry.spec.skip.js
test/backward/v1.11.1.compat.js
test/resourceStore.spec.js
test/translator/translator.translate.systemProperties.spec.js

* Clean language code before passing to formatters, to avoid errors like this when using locale like `'en_US'`:
```
RangeError: Incorrect locale information provided
at new ListFormat (<anonymous>)
at i18next.js:1430:27
```
* Fix misc typos

Clean language code before passing to formatters; fix some typos

---

index.d.ts
test/typescript/custom-types/t.test.ts

Previously, two `TFunction` types would be treated as compatible even if they referred to different namespaces. For example:
```ts
function bar(t: TFunction<"bar">) { }
const { t } = useTranslation("foo");
bar(t); // wrong, but no TS error :(
```
This PR adds a property to the `TFunction` interface, making it a ["branded" type](https://medium.com/@KevinBGreene/surviving-the-typescript-ecosystem-branding-and-type-tagging-6cf6e516523d). Two `TFunction`s with different values of `Ns` will no longer be treated as compatible. The example above will now fail to compile.
Fixes #1941

Add brand to TFunction type so different namespaces' TFunctions are not treated as compatible

---

index.d.ts
package.json
test/typescript/custom-types/t.test.ts
test/typescript/default-types/t.test.ts
test/typescript/default-types/tsconfig.json
tsconfig.json

Follow-up to #1994 
Fix type brand validation for more complex TFunction use cases (like `TFunction<["a", "b"]>`).

Fix $TFunctionBrand for non-string namespaces

---

index.d.ts

Closes https://github.com/i18next/i18next/issues/1991
In this PR, I've simplified the approach for inferring the return type by directly returning the value of a specified key, rather than using conditional type to verify the presence of all `KeyWithOrdinalPlural`, `KeyWithPlural`, and `Key` within `Res` before returning the value.
Here are the complexity results for the old and new approaches:
- N = Number of sub-keys in the same key or namespace
- KeyWithPlural = 6
- KeyWithOrdinalPlural = 6
**Complexity:** O((KeyWithPlural * N) + (KeyWithOrdinalPlural * N) + N) = O(13 * N)
**Complexity:** O(1) - constant time

Fix performance issue that affects flat object with multiple (thousands) keys

---

package.json
test/typescript/custom-context-separator/i18next.d.ts
test/typescript/custom-context-separator/t.test.ts
test/typescript/custom-context-separator/tsconfig.json
tsconfig.json
typescript/options.d.ts
typescript/t.d.ts

Allow usage of custom `contextSeparator` in `CustomTypeOptions` for correctly resolving keys in typescript.
Added a new folder `custom-context-separator` in `test/typescript` to test this specific scenario.
Fixes #2016

types: add customisation of `contextSeparator`

---

typescript/t.v4.d.ts

I just noticed there is a separate `t` type function file for typescript@4.
I added #2017 patch to that file.

types: add contextSeparator also on v4 t types

---

test/typescript/custom-types/t.test.ts
test/typescript/t.test.ts
typescript/helpers.d.ts
typescript/options.d.ts
typescript/t.d.ts

While upgrading to v23 we encounter the same issue described in #2011.
The problem seems caused by `any` usage in defaultValue, interpolation map and dictionary.
Changing them to `unknown` should make type infer from nested `t` work properly.
We have tested this patch on our repository and it seems to be working.

types: use unknown to better infer types on nested t functions

---

src/Translator.js
test/translator/translator.translate.spec.js
test/typescript/t.test.ts
typescript/t.d.ts
typescript/t.v4.d.ts

Fixes https://github.com/i18next/i18next/issues/2046
What was changed?
1. Added a new field (`usedParams`) to the object returned from `t()` when `returnDetails = true`. It should contain all the fields passed to interpolation.

add interpolation data to response if returnDetails is true

---

test/typescript/format.test.ts
typescript/options.d.ts

Fixes #2074
I might been able to develop a more sophisticated solution using interface augmentation to allow user extends interpolation options so you can get type checking and autocomplete also on `t`  alongside `FormatFunction` type.
However I never used them so I need to check how they work.

fix(types): FormatFunction should allow any value inside options parameter

---

index.d.ts

Addressing this issue:
https://github.com/i18next/i18next/issues/2087
initializedStoreOnce and initializedLanguageOnce are now public

exposed initializedStoreOnce and initializedLanguageOnce props

---

.circleci/config.yml
.codeclimate.yml

Follow up to #2098.
Added a `lint` to job to `circleci` and disabled eslint on `codeclimate`

chore: move linting to codeclimate to circleci

---

test/typescript/array-access/i18next.d.ts
test/typescript/array-access/t.test.ts
test/typescript/array-access/tsconfig.json
typescript/t.d.ts
typescript/t.v4.d.ts

The typing for accessing arrays was broken (yielding type errors on any access) and should be fixed with this PR. This should fix #2040 - I hope I spotted all the edge cases.

fix types for array access

---

test/typescript/array-access/i18next.d.ts
test/typescript/array-access/t.test.ts
typescript/t.d.ts
typescript/t.v4.d.ts

I noticed one edge case was missing in yesterdays #2101 - it was an easy fix tho. Now the sandbox example provided in #2040 should actually be fixed as well.

fix types for readonly array access

---

package.json

Tests are still passing because the v5 types are also valid. I'm not sure how should I write a test to check if the type file used matches the typescript version.

fix: Use Typescript 5 types with Typescript 5+

---

.npmignore
CONTRIBUTING.md
package.json
test/local/backend/backendConnector.load.retry.test.js
test/local/backend/backendConnector.perfErrorRetries.test.js
vitest.workspace.local.mts

Followup to #2017 [comment](https://github.com/i18next/i18next/pull/2107#issuecomment-1876921271):
What is the best way to run `test/runtime/**/*.test.local.*` tests? 
Now you can use:
```bash
npm run test:local
```
---

test: add `local` workspace

---

.eslintrc.js
package.json
test/compatibility/v1.js
test/runtime/backend/backendMockPromise.js
test/runtime/backend/backendMockSync.js
test/runtime/i18next.extendTranslation.test.js
test/runtime/interpolation.test.js
test/runtime/translator/translator.cimode.test.js
test/runtime/translator/translator.exists.test.js
test/runtime/translator/translator.translate.separator.test.js
test/typescript/array-access/t.test.ts
test/typescript/custom-types/mock.test.ts
test/typescript/many-keys/parseKeys.perf.ts
test/typescript/misc/exposed.test.ts
test/typescript/misc/init.test.ts
test/typescript/misc/modules.test.ts
test/typescript/misc/t.test.ts
test/typescript/misc/tGeneric.test.ts

ESLint now includes also `test` directory
The most notable change is `test/typescript/misc/init.test.ts` rewrite.
During #2097 I have miss out the file so it wasn't using any type assertion.

refactor: enable eslint in test directory

---

CONTRIBUTING.md
index.d.ts
test/typescript/array-access/i18next.d.ts
test/typescript/array-access/t.test.ts
test/typescript/custom-types-default-ns-as-array/i18next.d.ts
test/typescript/custom-types-default-ns-as-array/i18nextT.test.ts
test/typescript/custom-types-default-ns-as-array/t.test.ts
test/typescript/custom-types-default-ns-as-array/tsconfig.json
test/typescript/custom-types-json-v3/i18next.d.ts
test/typescript/custom-types/i18next.d.ts
test/typescript/custom-types/t.test.ts
test/typescript/many-keys/PERF_README.md
test/typescript/test.namespace.samples.ts
typescript/helpers.d.ts
vitest.workspace.mts

Fixes #2118.
The main difference from #2119 is that I tried to take into account all namespaces included in `defaultNS` when providing it as an array.
----
Before marking this PR ready for review I would like to see what I can do to deduce test code. 
I hope to have something ready tomorrow.

types: fix support for defaultNS as array (fixes #2118)

---

index.d.ts

During #2121 I noticed a typo in `CustomInstanceExtensions` so I corrected it.
I don't know if this should be considered a breaking change or a bug but there is no mention in the doc of this interface (https://www.i18next.com/?q=CustomInstanceExtensions), hence I think it can be considered a fix.
- (N/A) tests are included

types: fix typo in `CustomInstanceExtensions`

---

test/typescript/custom-types-default-ns-as-array/i18next.d.ts
typescript/helpers.d.ts

Follow-up of #2121 to also allow defaultNS to be readonly (This is the case when using `as const` on the defaultNS definitions and using typeof defaultNS in the types)

types: support readonly defaultNS

---

src/EventEmitter.js
src/Interpolator.js
src/ResourceStore.js
src/utils.js
test/runtime/eventEmitter.test.js
test/runtime/utils.test.js

Our app recently switched to using i18next. It works great, but the app felt slower. We have hundreds of strings on-screen at a time, so i18next code is run a lot.
After profiling, some i18next functions were the top contributors to time taken within our 20s stacktrace:
- `off`: used by react-i18next (and base library i18next) for detaching event handlers on unmount. It looks like it calls a array.filter according to [source code](https://github.com/i18next/i18next/blob/26844609a8bfa8db7b7c62b58329f3e9a7a3694a/src/EventEmitter.js#L14). This may be iterating through a very large array
- `getLastOfPath`: 158ms - [code](https://github.com/i18next/i18next/blob/26844609a8bfa8db7b7c62b58329f3e9a7a3694a/src/utils.js#L29) does a lot of recursive retrieval and also creates a RegExp, which may take …

Improve performance by reducing array slices and RegExp recreation

---

test/typescript/custom-types-default-ns-as-array/i18nextT.test.ts
test/typescript/custom-types-edited-returns/i18next.d.ts
test/typescript/custom-types-edited-returns/t.test.ts
test/typescript/custom-types-edited-returns/tsconfig.json
test/typescript/custom-types-json-v3/i18nextT.test.ts
test/typescript/custom-types/i18nextT.test.ts
test/typescript/custom-types/t.test.ts
test/typescript/test.namespace.samples.ts
typescript/options.d.ts
typescript/t.d.ts
typescript/t.v4.d.ts

This is an adaptation of #2000 addressing the feedback and rebasing.
For TypeScript users who are using key fallback (`returnEmptyString` or `returnNull` set to false), the improved type inference introduced in v23 isn't working at the moment. This PR fixes that.
Check the `returnEmptyString` and `returnNull` settings when deciding whether we can return null/empty string or fallback to the key.
Added tests; ran on a large codebase and verified it typechecked still

types: support stricter typechecking for returnEmptyString and returnNull

---

test/typescript/custom-types/i18next.d.ts
test/typescript/custom-types/t.test.ts
test/typescript/test.namespace.samples.ts
typescript/helpers.d.ts
typescript/t.d.ts
typescript/t.v4.d.ts

Fixes #2014
Now `InterpolatorMap` parse the keys retrieved via `ParseInterpolationValues` creating a mapped type instead of a a `Record<string, unknown>`.
Here is a typescript playground where all types involved are available:
- Open [Playground](https://www.typescriptlang.org/play?ts=5.3.3#code/KYDwDg9gTgLgBDAnmYcAkAFKwDOwoBuwAJgGoCGANgK7AA8FNwANHAGJWUBG5AxgNYA+OAF44AbUa0AunFAxgAO2I4Ji4ESiyA-O048BcAFxwpwANwAoSwHoAVHctw7cAAJIUGclHIBbOAAqTi6uoH5glMDBcAAGcdFoAKqKAJYQigEQAJKKClB4vDBpinQA3gBmEBAmpTxQJjgwUCmKAOYAvnAAPnCl5DjEJlxVkeSK7e3CYhVVNXUNTS0dcABkvf2DcMMQo+Pt0XEx0dGueKgAFjAwYDhGNjaNfPwQmuWUEADuAHS8EL42AEdaI1ijgbABWAAMAGYAOwAFgAnJCABw2JpjHCVKC+AC01FS6VxHmAxIguJaeQKRSJJOCNksJPQyWKmRyVOAhWKdACUzgAAoAnIQAplKoCfxFJ9FHBdPz+CYAgBKUTCAgQFLEYxwdSaFXyJQqAVOOAKuAtcr4OBZZiWFUiNUa4gm3RZE0mXX4Ky2BwnEleH …

types: support nested keys in `InterpolationMap`

---

i18next.js

When using `i18next` in an environment where Intl and Intl.PluralRules are not available we need to polyfill them.
When using `intl` and `intl-pluralrules` package, we also need to include locale data for the language we want like `intl/locale-data/jsonp/fr.js` (see [here](https://github.com/andyearnshaw/Intl.js/tree/master?tab=readme-ov-file#intljs-and-browserifywebpack)). If we do not do it, pluralization will fail silently and we will only get a `no plural rule found for: fr` warn log. 
In this PR, I add a new log in the catch where we try to get the PluralRules. It helps debugging. It allowed to display a new and more explicit `No locale data has been provided` warn log in my case .

fix: log error when Intl.PluralRules error

---

package-lock.json
package.json
tsconfig.json
typescript/t.d.ts

Fixes #2168
- Remove `const` `Context` type parameter of `ParseKeys` type
- Update `typescript` to `5.4.4`
- to prevent silent error on `*.d.ts` that won't be catched by ts tests, 
`tsconfig.json` `compilerOptions.skipLibCheck` has been changed to `false`.
- Update `tsconfig.json` `module` and `moduleResolution`  using "modern" values.

types: remove const from ParseKeys Context type parameter and disable `skipLibCheck`

---

test/typescript/custom-types/t.test.ts
tsconfig.json

Add tests for context values from an `enum` value. (Related to #2172)

test(types): add context values with enums

---

src/Interpolator.js

The code used in this file can benefit from the use of object deconstruction and optional changing. Both of these reduce the amount of property lookups the engine needs to do which should help improve performance. Perhaps more important it cuts out unneeded code and allows for better mangling by rollup, cutting down the size of the minified files a bit, without impacting functionality.

perf(interpolator): use object deconstruction

---

test/typescript/custom-types/t.test.ts
test/typescript/test.namespace.samples.ts

Added few more tests for `context` with or without context value

types: add test for accessing a context default value

---

.eslintrc.js
package-lock.json
package.json
rollup.config.mjs
tsconfig.lint.json
vitest.config.mts
vitest.workspace.local.mts
vitest.workspace.mts
vitest.workspace.typescript.mts

I just noticed that on my machine `@typescript-eslint` was throwing a warning:
```text
> i18next@23.11.4 lint
> eslint src typescript test "./*.{ts,mts}"
=============
WARNING: You are currently running a version of TypeScript which is not officially supported by @typescript-eslint/typescript-estree.
You may find that it works just fine, or you may not.
SUPPORTED TYPESCRIPT VERSIONS: >=4.3.5 <5.4.0
YOUR TYPESCRIPT VERSION: 5.4.4
Please only submit bug reports when using the officially supported version.
=============
```
In this PR:
- `eslint` has been updated to `8.57.0` (can't use v9 since config airbnb doesn't support it yet)
- `@typescript-eslint/{eslint-plugin|parser}` have both been updated to `7.8.0`
- `mjs` files added to format and lint commands
- …

chore: update eslint and @typescript/eslint packages

---

test/typescript/custom-types/i18next.d.ts
test/typescript/custom-types/t.test.ts
test/typescript/test.namespace.samples.ts

Added new tests for `context`:
- usage with namespace prefix in `t` key
- usage of context value with the same `t` function from two different namespaces

types: add tests for context values

---

test/typescript/custom-types/t.test.ts

This should be the last test that needs to be added to fill the gap discovered in #2182
https://github.com/i18next/i18next/pull/2182#pullrequestreview-2055968571 ("Default context value" section)

types: add test for context with default value

---

src/Formatter.js

Trims the key once and reuse it rather than calling trim multiple times. Also moves the logic inside the if condition instead of using an early return since it's the only logic in there.
This should improve both the performance and bundle size a tiny bit.

perf: trim keys once

---

src/LanguageUtils.js
src/ResourceStore.js
src/Translator.js

Uses `Array.isArray(obj)` instead of `Object.prototype.toString.apply(object) === '[object Array]'` for a small performance and bundle size gain.
By utilising the new native builtin supported by all target browsers we can reduce the previous 3 step operation to 1 step.

perf: use Array.isArray()

---

index.d.ts
test/typescript/misc/i18nInstance.test.ts

`i18n.hasLoadedNamespace` has two definitions.
Comparing the definition with the js implementation the two definition can be merged with a single one.
https://github.com/i18next/i18next/blob/c8d9f7bbc77ccb1bc1f24272827afd9295281756/src/i18next.js#L426-L463
I also added relevant definition tests.
---
> [!NOTE]  
> `test/typescript/misc/init.test.ts` has been renamed to `test/typescript/misc/i18nInstance.test.ts` to better reflect the file content

types: merge `hasLoadedNamespace` declarations

---

package-lock.json
package.json
tsconfig.json
vitest.workspace.typescript.mts

[Update `vitest` to v2](https://vitest.dev/guide/migration.html#migrating-to-vitest-2-0)
No changes are required expect to add `@types/node` package to avoid types error when running `ts` tests.
Local workspace tests are working:
----
> [!NOTE]
> Enabled `skipDefaultLibCheck` to avoid type checking on default `ts` libs.
> It should give a slight performance improvement on `ts` tests.

test: update vitest to v2

---

src/BackendConnector.js
src/Interpolator.js
src/ResourceStore.js
src/Translator.js
test/runtime/utils.test.js

Changes the star imports (import `*`) to explicitly import the utils that are used in each file, this helps with dead code elimination and some code in the resulting build from:
```js
function pushPath(object, path, newValue, concat) {
const {
obj,
k
} = getLastOfPath(object, path, Object);
obj[k] = obj[k] || [];
if (concat) obj[k] = obj[k].concat(newValue);
if (!concat) obj[k].push(newValue);
}
```
to:
```js
function pushPath(object, path, newValue, concat) {
const {
obj,
k
} = getLastOfPath(object, path, Object);
obj[k] = obj[k] || [];
obj[k].push(newValue);
}
```
This is because concat is not actually passed to the util function which means the build process can remove the branching as it will always have a deterministic output.
If that changes in the future the code will once again be …

Use explicit imports for utils

---

i18next.js
src/PluralResolver.js
test/runtime/pluralResolver.test.js

While profiling scrolling our app, we saw that this function was taking a long time. This is because in React Native and possibly other runtimes, calling Intl functions can be slow.
Cached the output of getRule to improve performance.
Using a consistent test process of scrolling 20 seconds in our app at the same starting point and then restarting the app after each trial, we measured the cumulative time that getRule was taking. The performance improvement is significant, whereas the memory usage difference was negligible since most apps ever use a 1 to a few codes per run, this cached object is tiny. The total universe is # codes * 2, which is still very small.
  | Time 1(ms) | Time 2(ms) | Time 3(ms)
-- | -- | -- | --
Before(no caching) | 630 | 581 | 619
After(with caching) | 2 | 2 | 3

Cache output of getRule to optimize performance

---

examples/typescript/i18n/en/ns1.ts
examples/typescript/index.ts
test/typescript/custom-types-json-v3/i18nextT.test.ts
test/typescript/test.namespace.samples.ts
typescript/options.d.ts
typescript/t.d.ts
typescript/t.v4.d.ts

Support unescaped variables in TypeScript when parsing actual values.
Without this fix, the variable names parsed in TypeScript will include the unescaped prefix/suffix, for example:
```
"locale": "Something {{- var}}"
```
```
t("locale", { "- var": value })
```
instead of:
```
t("locale", { var: value })
```

support unescaped variables in TypeScript

---

test/typescript/custom-types-default-ns-as-array/i18nextT.test.ts
test/typescript/custom-types-default-ns-as-array/t.test.ts
test/typescript/custom-types-json-v3/i18nextT.test.ts
test/typescript/custom-types-json-v3/t.test.ts
test/typescript/custom-types/i18nextT.test.ts
test/typescript/custom-types/t.test.ts
test/typescript/misc/t.test.ts
typescript/helpers.d.ts
typescript/t.d.ts

Close #2232
Now `TFunction` do not infer return type. In addition if defaultValue is provided and the key is not mapped in `Resources` the return type of the `TFunction` will be inferred by `DefaultValue`.

types(TFunction): make return not inferrable and use defaultValue as return when provided

---

test/typescript/custom-types-json-v3/i18nextT.test.ts
test/typescript/custom-types/i18nextT.test.ts

- Few types refinements on `defaultValue` tests  related to  #2234
- Sync i18nT tests between `custom-types` and `custom-types-v3` workspaces

test(types): align and refine defaultValue test types

---

test/typescript/custom-types/t.test.ts
test/typescript/many-keys/PERF_README.md
typescript/options.d.ts
typescript/t.d.ts

Close #2242
----
Now `FilterKeysByContext` is more strict and should not suggest "stripped" keys  like reported in #2242
---
Considering the following namespace:
```ts
export type TestNamespaceContext = {
dessert_cake: 'a nice cake';
dessert_muffin_one: 'a nice muffin';
dessert_muffin_other: '{{count}} nice muffins';
beverage: 'a classic beverage';
beverage_beer: 'fresh beer';
beverage_water: 'cold water';
};
```
`dessert` context related keys have no default and with the current type architecture 
the `dessert` key can't be showed in suggestion. On the contrary all context values can.
E.g.:

fix(types): make context related keys detection stricter

---

README.md

Hello team,
I'm the maintainer of [Anteon](https://github.com/getanteon/anteon). We have created Gurubase.io with the mission of building a centralized, open-source tool-focused knowledge base. Essentially, each "guru" is equipped with custom knowledge to answer user questions based on collected data related to that tool.
I wanted to update you that I've manually added the [i18next Guru](https://gurubase.io/g/i18next) to Gurubase. i18next Guru uses the data from this repo and data from the [docs](https://www.i18next.com) to answer questions by leveraging the LLM.
In this PR, I showcased the "i18next Guru", which highlights that i18next now has an AI assistant available to help users with their questions. Please let me know your thoughts on this contribution.
Additionally, if you want me …

Introducing i18next Guru on Gurubase.io

---

CHANGELOG.md

Follow up to #2253
- I forgot to add a changelog entry for typescript 4 support removal
- fix a typo

feat: add changelog for typescript version update

---

src/PluralResolver.js

This PR extends the fallback flow discussed in https://github.com/i18next/i18next/issues/2252 by creating a cache entry for custom language codes.
This avoids a cache miss that would otherwise happen for every invocation with an invalid language code.

fix(plural): Create cache entry for PluralRules created as part of the fallback flow

---

test/typescript/misc/exposed.test.ts

Related to https://github.com/i18next/i18next/pull/2259#issuecomment-2490842688
@adrai  your fix was good 😉. 
Few minor additions:
- Removed redundant assertion 
(`expectTypeOf(i18next.on).toMatchTypeOf<...>()` already checks the return type)
- Added a comment explaining why this assertion is different from the others

types: refine `i18next.on` type assertion after `vitest` update

---

src/LanguageUtils.js
test/runtime/languageUtils.test.js

Some language detectors may return invalid languages which cause `Intl.getCanonicalLocales` to throw. In this case, we need to swallow the error and ignore the detected language.

fix: incorrect locale detected

---

typescript/t.d.ts

Change `TFunction` typing back into `interface` so it can be augmentable, wrapping the actual type in `TFunctionSignature`. Would fix #2278 (? need to verify)

fix(typescript): make `TFunction` augmentable

---

i18next.js
src/Translator.js

Fixes #2310.
I tried to make the `nsSeparator` checks consistent with the ones in `extractFromKey`.

Ensure `nsSeparator` is respected when `appendNamespaceToMissingKey` is `true`

---

index.d.ts
src/index.js

exports `keyFromSelector` function for testing purposes
